communications/urls.py
from django.urls import path
from . import views

app_name = 'communications'

urlpatterns = [
    path('comm_detail/<int:uuid>/', views.comm_detail, name="comm-detail"),
    path('add_comm/', views.add_comm, name="add-comm"),
    path('edit_comm/<int:uuid>/', views.edit_comm, name="edit-comm"),
    path('delete_comm/<int:uuid>/', views.delete_comm, name="delete-comm"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('marketing.urls', namespace='marketing')),
    path('ledger/', include('ledger.urls', namespace='ledger')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('communications/', include('communications.urls', namespace='communications'))
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

communications/models.py
from django.db import models
from django.contrib.auth import get_user_model
from shortuuidfield import ShortUUIDField

from ledger.models import Ledger

# Create your models here.

User = get_user_model()

class Communication(models.Model):
    TYPE = (
        (1, 'Meeting'),
        (2, 'Phone'),
        (3, 'Email'),
    )
    uuid = ShortUUIDField(unique=True)
    subject = models.CharField(max_length=50)
    notes = models.TextField()
    kind = models.PositiveSmallIntegerField(choices=TYPE)
    date = models.DateField()
    ledger = models.ForeignKey(Ledger, on_delete=models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_on =  models.DateField(auto_now_add=True)

    def __str__(self):
        return self.subject

communications/forms.py
from django import forms
from django.forms import ModelForm
from .models import Communication

class DateInput(forms.DateInput):
    input_type = 'date'

class CommunicationForm(ModelForm):
    class Meta:
        model = Communication
        fields = '__all__'
        exclude = ('uuid', 'owner', 'created_on', 'ledger',)
        widgets = {'date': DateInput}
            

communications/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from .models import Communication
from .forms import CommunicationForm

# Create your views here.

@login_required(login_url='account_login')
def comm_detail(request, uuid):
    comm = Communication.objects.get(pk=uuid)
    return render(request, 'communications/comm_detail.html', {'comm': comm})

@login_required(login_url='account_login')
def add_comm(request):
    form = CommunicationForm

    if request.method == 'POST':
        form = CommunicationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect()
    return render(request, 'communications/comm_cru.html', {'form': form})

@login_required(login_url='account_login')
def edit_comm(request, uuid):
    comm = Communication.objects.get(pk=uuid)
    form = CommunicationForm(instance=comm)

    if request.method == 'POST':
        form = CommunicationForm(request.POST, instance=comm)
        if form.is_valid():
            form.save()
            return redirect()
    return render(request, 'communications/comm_cru.html', {'form': form})

@login_required(login_url='account_login')
def delete_comm(request, uuid):
    comm = Communication.objects.get(pk=uuid)

    if request.method == 'POST':
        comm.delete()
        return redirect()
    return render(request, 'delete_obj.html', {'obj': comm})

docs/templates/communications/comm_cru.html
{% extends 'base.html' %}

{% block title %}Communication Operation{% endblock %}
{% block content %}
    <div>
        <div>
            <h4>Add a Communication</h4>
            {% include 'communications/comm_item_form.html' %}
        </div> 
    </div>
{% endblock %}

docs/templates/communications/comm_detail.html
{% extends 'base.html' %}

{% block title %}Communication Detail{% endblock %}
{% block content %}
    <div>
        {% include 'communications/comm_item_view.html' %} 
    </div>
{% endblock %}

docs/templates/communications/comm_item_form.html
<div>
    <form action="" autocomplete="off" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <button type="submit">Submit</button>
    </form>
</div>

docs/templates/communications/comm_item_view.html
<ul>
    <li>
        <h5>{{comm.subject}}
            <span>
                <a href="{% url 'communications:edit-comm' comm.pk %}">Edit</a>
                <a href="{% url 'communications:delete-comm' comm.pk %}">Delete</a>
            </span>
        </h5>
        <p>on {{comm.date}}</p>
        <p>{{comm.notes}}</p>
    </li>        
</ul>