config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('marketing.urls', namespace='marketing')),
    path('ledger/', include('ledger.urls', namespace='ledger')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('communications/', include('communications.urls', namespace='communications'))
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('contact_detail/<int:uuid>/', views.contact_detail, name="contact-detail"),
    path('add_contact/', views.add_contact, name="add-contact"),
    path('edit_contact/<int:uuid>/', views.edit_contact, name="edit-contact"),
    path('delete_contact/<int:uuid>/', views.delete_contact, name="delete-contact"),
]

ledger/urls.py
from django.urls import path
from . import views
from .views import AccountListView

app_name = 'ledger'

urlpatterns = [
    path('account_list/', AccountListView.as_view(), name="account-list"),
    path('account_detail/<int:uuid>/', views.account_detail, name="account-detail"),
    path('add_account/', views.add_account, name="add-account"),
    path('edit_account/<int:uuid>/', views.edit_account, name="edit-account"),
]

ledger/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth import get_user_model
from shortuuidfield import ShortUUIDField

# Create your models here.

User = get_user_model()

class Ledger(models.Model):
    uuid = ShortUUIDField(unique=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    email = models.EmailField()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    address_one = models.CharField(max_length=100)
    address_two = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    created_on =  models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'ledger'

    def __str__(self):
        return self.name

ledger/forms.py
from django.forms import ModelForm, TextInput
from .models import Ledger

class AccountForm(ModelForm):
    class Meta:
        model = Ledger
        fields = '__all__'
        exclude = ('uuid', 'owner', 'created_on',)
        widgets = {'phone_number': TextInput(attrs={
            'placeholder': 'e.g +234'
            })}

ledger/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Ledger
from .forms import AccountForm

from contacts.models import Contact
from communications.models import Communication
from communications.forms import CommunicationForm

# Create your views here.

@method_decorator(login_required, name='dispatch')
class AccountListView(ListView):
    paginate_by = 10
    template_name = 'ledger/account_list.html'
    context_object_name = 'ledgers'

    def get_queryset(self):
        q = self.request.GET.get('q')
        if q:
            account_list = Ledger.objects.filter(
                name__icontains=q
            ).order_by('-created_on')
        else:
            account_list = Ledger.objects.all().order_by('-created_on')
        return account_list

@login_required(login_url='account_login')
def account_detail(request, uuid):
    ledger = Ledger.objects.get(pk=uuid)
    contacts = Contact.objects.filter(ledger=ledger)
    communications = Communication.objects.filter(
        ledger=ledger).order_by('-created_on')
    form = CommunicationForm
    context = {
        'ledger': ledger,
        'contacts': contacts,
        'communications': communications,
        'form': form,
    }
    return render(request, 'ledger/account_detail.html', context)

@login_required(login_url='account_login')
def add_account(request):
    form = AccountForm

    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ledger:account-list')
    return render(request, 'ledger/account_cru.html', {'form': form})

@login_required(login_url='account_login')
def edit_account(request, uuid):
    ledger = Ledger.objects.get(pk=uuid)
    form = AccountForm(instance=ledger)

    if request.method == 'POST':
        form = AccountForm(request.POST, instance=ledger)
        if form.is_valid():
            form.save()
            return redirect('ledger:account-list')
    return render(request, 'ledger/account_cru.html', {'form': form})
   

docs/templates/ledger/account_cru.html
{% extends 'base.html' %}

{% block title %}Account Operation{% endblock %}
{% block content %}
    <div>
        <div>
            <h4>Add an Account</h4>
            {% include 'ledger/account_item_form.html' %}
        </div> 
    </div>
{% endblock %}

docs/templates/ledger/account_detail.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div>
            <div>
                {% include 'ledger/account_item_view.html' %}
            </div> 
        </div>
        <div>
            <div>
                <h4>Contacts</h4>
            </div>
            <div>
                <table>
                    <tbody>
                        <tr></tr>
                        {% for contact in contacts %}
                            {% include 'contacts/contact_item_view.html' %}
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'contacts:add-contact' %}">New Contact</a>
            </div>
        </div>
        <div>
            <div>
                <h4>Communications</h4>
            </div>
            <div>
                <div>
                    {% include 'communications/comm_item_form.html' %}
                </div>
                {% for comm in communications %}
                    {% include 'communications/comm_item_view.html' %}
                {% endfor %}
            </div>
        </div>
        <a href="{{request.META.HTTP_REFERER}}">Back</a>
    </div>
{% endblock %}

docs/templates/ledger/account_item_form.html
<div>
    <form action="" autocomplete="off" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
        <a href="{{request.META.HTTP_REFERER}}">Back</a>
    </form>
</div>
        
            
        
        

docs/templates/ledger/account_item_view.html
<h3>{{ledger.name}}
    <span>
        <a href="{% url 'ledger:edit-account' ledger.pk %}">Edit</a>
    </span>
</h3>

<div>
    <div>
        <h5>Description</h5>
        <p>{{ledger.description}}</p>
    </div>
    <div>
        <h5>Address</h5>
        <p>{{ledger.address_one}}</p>
        <p>{{ledger.address_two}}</p>
        <p>{{ledger.city}}, {{ledger.state}}</p>
        <p>{{ledger.email}}</p>
        <p>{{ledger.phone_number}}</p>
    </div>
</div>

docs/templates/ledger/account_list.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div>
            <h3>Account List
                <span>
                    <a href="{% url 'ledger:add-account' %}">+ Add new Account</a>
                </span>
            </h3>
            <form action="{% url 'ledger:account-list' %}" method="get">
                <input type="text" name="q" placeholder="search">
            </form>    
        </div>        
        {% for ledger in ledgers %}
            <ul>
                <li>
                    <a href="{% url 'ledger:account-detail' ledger.pk %}"><h4>{{ledger.name}}</h4></a>
                    <span>created on {{ledger.created_on}}</span>
                </li>
            </ul>
        {% endfor %}
        <div class="pagination">
            <span>
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo;first</a>
                    <a href="?page={{page_obj.previous_page_number}}">previous</a>
                {% endif %}
                <span>
                    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{page_obj.next_page_number}}">next</a>
                    <a href="?page={{page_obj.paginator.num_pages}}">last &laquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}