config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('marketing.urls', namespace='marketing')),
    path('ledger/', include('ledger.urls', namespace='ledger')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('communications/', include('communications.urls', namespace='communications'))
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ledger/urls.py
from django.urls import path
from . import views
from .views import AccountListView

app_name = 'ledger'

urlpatterns = [
    path('account_list/', AccountListView.as_view(), name="account-list"),
    path('account_detail/<int:uuid>/', views.account_detail, name="account-detail"),
    path('add_account/', views.add_account, name="add-account"),
    path('edit_account/<int:uuid>/', views.edit_account, name="edit-account"),
]

marketing/urls.py
from django.urls import path
from .views import IndexView 

app_name = 'marketing'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
]

docs/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>{% block title %}Home {% endblock title %} | CRM</title>  
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  </head>
  <body>
    <div>
      <header>
        <div>
          <button>
            <span></span>
            <span></span>
            <span></span>
          </button>
          <a href="{% url 'marketing:index' %}">CRM</a>
        </div>
        <div>
          <ul>
            {% if user.is_authenticated %}
              <li><a href="{% url 'account_logout' %}">Logout</a></li>
              <li><a href="{% url 'ledger:account-list' %}">Accounts</a></li>
            {% else %}
              <li><a href="{% url 'account_login' %}">Login</a></li>
              <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </header>
    </div>
    <div>
      {% block content %}
        if you're seeing this, something's wrong        
      {% endblock content %}
    </div>
    <footer>
      <p>Copyright CRM</p>
    </footer>
  </body>
  {% block scripts %}
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
  {% endblock scripts %}
</html>

docs/templates/delete_obj.html
{% extends 'base.html' %}

{% block title %}Confirm delete{% endblock %}
{% block content %}    
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <h2>Are you sure?</h2>
            <p>You are about to delete {{obj}}. Please confirm.</p>
            <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

docs/templates/index.html
{% extends 'base.html' %}

{% block content %}    
    <div>
        <div>
            <div>
                <h1>Never Miss Another Opportunity</h1>
            </div>
            <div>
                <p>A CRM application that lets you track
                all of your customers, meetings, notes,
                and plans. Never forget an important
                contact or follow up task again.</p>
            </div>
            <div>
                {% if not user.is_authenticated %}
                    <a href="{% url 'account_signup' %}"
                    class="">Sign Up Now!</a>
                {% else %}
                    <a href="{% url 'ledger:account-list' %}"
                    class="">Accounts</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}