config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('marketing.urls', namespace='marketing')),
    path('ledger/', include('ledger.urls', namespace='ledger')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('communications/', include('communications.urls', namespace='communications'))
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('contact_detail/<int:uuid>/', views.contact_detail, name="contact-detail"),
    path('add_contact/', views.add_contact, name="add-contact"),
    path('edit_contact/<int:uuid>/', views.edit_contact, name="edit-contact"),
    path('delete_contact/<int:uuid>/', views.delete_contact, name="delete-contact"),
]

ledger/urls.py
from django.urls import path
from . import views
from .views import AccountListView

app_name = 'ledger'

urlpatterns = [
    path('account_list/', AccountListView.as_view(), name="account-list"),
    path('account_detail/<int:uuid>/', views.account_detail, name="account-detail"),
    path('add_account/', views.add_account, name="add-account"),
    path('edit_account/<int:uuid>/', views.edit_account, name="edit-account"),
]

templates/account_detail.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div>
        <div>
            <div>
                {% include 'account_item_view.html' %}
            </div> 
        </div>
        <div>
            <div>
                <h4>Contacts</h4>
            </div>
            <div>
                <table>
                    <tbody>
                        <tr></tr>
                        {% for contact in contacts %}
                            {% include contact_item_view.html' %}
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% contact:add-contact %}">New Contact</a>
            </div>
        </div>
        <div>
            <div>
                <h4>Communications</h4>
            </div>
            <div>
                <div>
                    {% include 'comm_item_form.html' %}
                </div>
                <ul>
                    {% for comm in communications %}
                        {% include 'comm_item_view.html' %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

templates/account_list.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <h3>Account List
        <span>
            <a href="{% url 'ledger:add-account' %}">+ Add new Account</a>
        </span>
    </h3>

    <form action="{% url 'ledger:account-list' %}" method="get">
        <input type="text" name="q" placeholder="search...">
    </form>

    <ul id="display-data">
        {% for ledger in ledgers %}
            <li>
                <a href="{% url 'ledger:account-detail' ledger.pk %}"><h4>{{ledger.name}}</h4></a>
                <span>created on {{ledger.created_on}}</span>
            </li>
        {% endfor %}
    </ul>
    <div class="pagination">
        <span>
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo;first</a>
                <a href="?page={{page_obj.previous_page_number}}">previous</a>
            {% endif %}
            <span>
                Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}">next</a>
                <a href="?page={{page_obj.paginator.num_pages}}">last &laquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

templates/client_cru.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <h2>Create Client:</h2>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <button type="submit">Create</button>
        </form>
    </div>
{% endblock %}

templates/comm_detail.html
{% extends 'index.html' %}
{% load static %}

{% block title %}Communication Detail{% endblock %}
{% block content %}
    <div>
        <ul>
            {% include 'comm_item_view.html' %}
        </ul> 
    </div>
{% endblock %}

templates/comm_item_form.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div>
        <form autocomplete="off" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <button type="submit">Submit</button>
        </form>
    </div>    
{% endblock %}

templates/comm_item_view.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <li>
        <h5>{{comm.subject}}
            <span>
                <a href=""></a>
                <a href=""></a>
            </span>
        </h5>
        <p>on {{comm.date}}</p>
        <p>{{comm.notes}}</p>
    </li>    
{% endblock %}

templates/contact_cru.html
{% extends 'index.html' %}
{% load static %}

{% block title %}Contact Operation{% endblock %}
{% block content %}
    <div>
        <div>
            {% include 'contact_item_view.html' %}
        </div> 
    </div>
{% endblock %}

templates/contact_detail.html
{% extends 'index.html' %}
{% load static %}

{% block title %}Contact Detail{% endblock %}
{% block content %}
    <div>
        <div>
            <h4>Contact Details</h4>
            <table>
                <tbody>
                    {% include 'contact_item_view.html' %}
                </tbody>
            </table> 
        </div>
    </div>
{% endblock %}

templates/contact_item_view.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<tr>
    <td>{{ contact.first_name }} {{ contact.last_name }}</td>
    <td>{{ contact.role }}</td>
    <td>{{ contact.email }}</td>
    <td>{{ contact.phone_number }}</td>
    <td>
        <a href="{% url 'contacts:edit-contact' contact.pk %}">Edit</a>
    </td>
    <td>
        <a href="{% url 'contacts:delete-contact' contact.pk %}">Delete</a>
    </td>
</tr>
{% endblock %}

templates/create_client.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <h2>Create Client:</h2>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <button type="submit">Create</button>
        </form>
    </div>
{% endblock %}

templates/cru_contact.html
{% extends 'index.html' %}
{% load static %}

{% block title %}Contact Operation{% endblock %}
{% block content %}
    <div>
        <div>
            {% include 'contact_item_view.html' %}
        </div> 
    </div>
{% endblock %}

templates/delete_client.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <h2>Delete Client:</h2>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <p>Delete {{obj}}?</p>
            <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

templates/delete_contact.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <h2>Delete Contact:</h2>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <p>Delete {{obj}}?</p>
            <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

templates/update_client.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <h2>Update Client:</h2>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <a href="{{request.META.HTTP_REFERER}}">Back</a>
            <button type="submit">Update</button>
        </form>
    </div>
{% endblock %}